name: Deployment
on:
  push;
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build
        env:
          CI: false
      - name: Copy files to Droplet(Apache2)
        run: | 
          scp -i ${{ secrets.DROPLET_SSH_KEY }} -r build/* ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_HOST }}:${{ secrets.DROPLET_REMOTE_PATH }}
      - name: SSH into droplet and restart Apache2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.APACHE_HOST}}
          username: ${{secrets.APACHE_USERNAME}}
          key: ${{secrets.DO_SSH_PRIVATE_KEY}}
          script: |
            sudo service apache2 restart
