name: Deployment
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        working-directory: react-app
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build
        env:
          CI: false
      - name: Deploy to Apache
        uses: appleboy/scp-action@master
        with:
          local: build
          remote: /var/www/html/build
          host: ${{ secrets.APACHE_HOST }}
          username: ${{ secrets.APACHE_USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
