name: Deployment
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build
        env:
          CI: false
      - name: Copy files to Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.APACHE_HOST}}
          username: ${{secrets.APACHE_USERNAME}}
          key: ${{secrets.DO_SSH_PRIVATE_KEY}}
          source: "build/*"
          target: "/srv/www/"
      - name: SSH into droplet and restart Apache2
        uses: appleboy/ssh-action@v0.7.0
        with:
          host: ${{secrets.APACHE_HOST}}
          username: ${{secrets.APACHE_USERNAME}}
          key: ${{secrets.DO_SSH_PRIVATE_KEY}}
          script: |
            sudo service apache2 restart
