name: Deployment
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build
        env:
          CI: false
      #- name: Copy files to Droplet(Apache2)
      - name: copy file via ssh key
        uses: Adars23/scp-actions
