name: Deployment
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build
        env:
          CI: false
      #- name: Copy files to Droplet(Apache2)
      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          port: ${{ secrets.DROPLET_PORT }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: build/*
          target: /var/www/html/build
          script: |
            sudo service apache2 restart
          
